src/main/java/br/com/casadocodigo/loja/models/Produto.java
package br.com.casadocodigo.loja.models;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
public class Produto {

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
    private int id;
	
	private String titulo;
	private String descricao;
	private int paginas;
	
	@DateTimeFormat
	private Calendar dataLancamento;

	@ElementCollection
	private List<Preco> precos = new ArrayList<>();
	
	private String sumarioPath;
	
	public Produto() {
	}
	
	public Produto(Integer id) {
		this.id = id; 
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getTitulo() {
		return titulo;
	}
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}
	public String getDescricao() {
		return descricao;
	}
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	public int getPaginas() {
		return paginas;
	}
	public void setPaginas(int paginas) {
		this.paginas = paginas;
	}
	public Calendar getDataLancamento() {
		return dataLancamento;
	}
	public void setDataLancamento(Calendar dataLancamento) {
		this.dataLancamento = dataLancamento;
	}
	public List<Preco> getPrecos() {
		return precos;
	}
	public void setPrecos(List<Preco> precos) {
		this.precos = precos;
	}
	public String getSumarioPath() {
		return sumarioPath;
	}
	public void setSumarioPath(String sumarioPath) {
		this.sumarioPath = sumarioPath;
	}
	
	@Override
	public String toString() {
		return "Produto [titulo=" + titulo + ", descricao=" + descricao + ", paginas=" + paginas + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Produto other = (Produto) obj;
		if (id != other.id)
			return false;
		return true;
	}
	
	public BigDecimal precoPara(TipoPreco tipoPreco) {
		return precos.stream().filter(preco -> preco.getTipo().equals(tipoPreco)).findFirst().get().getValor();
	}
}

src/main/java/br/com/casadocodigo/loja/models/Usuario.java
package br.com.casadocodigo.loja.models;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

@Entity
public class Usuario implements UserDetails {
	
	private static final long serialVersionUID = 1L;
	
	@Id
    private String email;
    private String nome;
    private String senha;
    @ManyToMany(fetch=FetchType.EAGER)
    private List<Role> roles = new ArrayList<Role>();
    
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getSenha() {
		return senha;
	}
	public void setSenha(String senha) {
		this.senha = senha;
	}
	public List<Role> getRoles() {
		return roles;
	}
	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}
	
	@Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return this.roles;
    }

    @Override
    public String getPassword() {
        return this.senha;
    }

    @Override
    public String getUsername() {
        return this.email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
	
}

src/main/java/br/com/casadocodigo/loja/controllers/ProdutosController.java
package br.com.casadocodigo.loja.controllers;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import br.com.casadocodigo.loja.daos.ProdutoDAO;
import br.com.casadocodigo.loja.infra.FileSaver;
import br.com.casadocodigo.loja.models.Produto;
import br.com.casadocodigo.loja.models.TipoPreco;
import br.com.casadocodigo.loja.validation.ProdutoValidation;

@Controller
@RequestMapping("/produtos")
public class ProdutosController {
	
	@Autowired
	private ProdutoDAO produtoDao;
	@Autowired
	private FileSaver fileSaver;
	
	@InitBinder
	public void initBinder(WebDataBinder binder){
		binder.addValidators(new ProdutoValidation());
	}

    @RequestMapping("/form")
    public ModelAndView form(Produto produto){
    	ModelAndView model = new ModelAndView("produtos/form");
    	model.addObject("tipos", TipoPreco.values());
        return model;
    }

    @RequestMapping(method=RequestMethod.POST)
    @CacheEvict(value="produtosHome", allEntries=true)
    public ModelAndView gravar(MultipartFile sumario, @Valid Produto produto, BindingResult result, RedirectAttributes redirectAttributes){
    	
    	if(result.hasErrors()){
    		return form(produto);
    	}
    	
    	String path = fileSaver.write("arquivos", sumario);
    	produto.setSumarioPath(path);
    	
        produtoDao.gravar(produto);
        redirectAttributes.addFlashAttribute("sucesso", "Produto cadastrado com sucesso.");
        
        return new ModelAndView("redirect:/produtos");
    }
    
    @RequestMapping(value="/remover", method=RequestMethod.POST)
    @CacheEvict(value="produtosHome", allEntries=true)
    public ModelAndView remover(Integer id){
    	
    	produtoDao.remover(id);
    	return new ModelAndView("redirect:/produtos");
    }
    
    @RequestMapping(method=RequestMethod.GET)
    public ModelAndView listar(){
    	ModelAndView modelAndView = new ModelAndView("produtos/lista");
    	modelAndView.addObject("produtos", produtoDao.listar());
    	return modelAndView;
    }
    
    @RequestMapping("/detalhe/{id}")
    public ModelAndView detalhe(@PathVariable Integer id) {
    	ModelAndView mav = new ModelAndView("produtos/detalhe");
    	Produto produto = produtoDao.find(id);
    	mav.addObject("produto", produto);
    	return mav;
    }
}

src/main/webapp/WEB-INF/views/produtos/form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security" %>

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	
	<c:url value="/resources/css" var="cssPath" />
	<link rel="stylesheet" href="${cssPath}/bootstrap.min.css" />
	<link rel="stylesheet" href="${cssPath}/bootstrap-theme.min.css" />
	
	<style type="text/css">
        body{
            padding-bottom: 60px;
        }
    </style>
	
	<title>Livros de Java, Android, iPhone, Ruby, PHP e muito mais - Casa do Código</title>
</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="${s:mvcUrl('HC#index').build()}">Casa do Código</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      	<ul class="nav navbar-nav">
	        	<li><a href="${s:mvcUrl('PC#listar').build()}">Lista de Produtos</a></li>
	        	<li><a href="${s:mvcUrl('PC#form').build()}">Cadastro de Produtos</a></li>
	    	</ul>
	    	<ul class="nav navbar-nav navbar-right">
				<li>
				    <a href="#">
				        <security:authentication property="principal" var="usuario"/>
				        Usuário: ${usuario.username}
				    </a>
				</li>
			</ul>
	    </div><!-- /.navbar-collapse -->
	  </div>
	</nav>
	<div class="container">
		<h1>Cadastro de Produtos</h1>
	    <form:form action="${s:mvcUrl('PC#gravar').build()}" method="post" commandName="produto" enctype="multipart/form-data">
	        <div class="form-group">
	            <label>Título</label>
	            <form:input path="titulo" cssClass="form-control" />
	            <form:errors path="titulo" />
	        </div>
	        <div class="form-group">
	            <label>Descrição</label>
	            <form:textarea path="descricao" cssClass="form-control" />
	            <form:errors path="descricao" />
	        </div>
	        <div class="form-group">
	            <label>Páginas</label>
	            <form:input path="paginas" cssClass="form-control" />
	            <form:errors path="paginas" />
	        </div>
	        <div class="form-group">
	            <label>Data de Lançamento</label>
	            <form:input path="dataLancamento" cssClass="form-control" />
	            <form:errors path="dataLancamento" />
	        </div>
	        
	        <c:forEach items="${tipos}" var="tipoPreco" varStatus="status">
	        	<div class="form-group">
		        	<label>${tipoPreco}</label>
		        	<form:input path="precos[${status.index}].valor" cssClass="form-control" />
		        	<form:hidden path="precos[${status.index}].tipo" value="${tipoPreco}" />
	        	</div>
	        </c:forEach>
	        
	        <div class="form-group">
			    <label>Sumário</label>
			    <input name="sumario" type="file" class="form-control" />
			</div>
	        
	        <button type="submit" class="btn btn-primary">Cadastrar</button>
	    </form:form>
    </div>
</body>
</html>

src/main/webapp/WEB-INF/views/produtos/lista.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security" %>

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	
	<c:url value="/resources/css" var="cssPath" />
	<link rel="stylesheet" href="${cssPath}/bootstrap.min.css" />
	<link rel="stylesheet" href="${cssPath}/bootstrap-theme.min.css" />
	
	<title>Livros de Java, Android, iPhone, Ruby, PHP e muito mais - Casa do Código</title>
</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="${s:mvcUrl('HC#index').build()}">Casa do Código</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    	<ul class="nav navbar-nav">
		        <li><a href="${s:mvcUrl('PC#listar').build()}">Lista de Produtos</a></li>
		        <li><a href="${s:mvcUrl('PC#form').build()}">Cadastro de Produtos</a></li>
	    	</ul>
	    	<ul class="nav navbar-nav navbar-right">
				<li><a href="#"><security:authentication property="principal.username"/></a></li>
			</ul>
	    </div><!-- /.navbar-collapse -->
	  </div>
	</nav>
	<div class="container">
		<h1>Lista de Produtos</h1>
		<p>${message}</p>
		<table class="table table-bordered table-striped table-hover">
			<tr>
				<th>Título</th>
	            <th>Descrição</th>
	            <th>Preços</th>
	            <th>Páginas</th>
			</tr>
			<c:forEach items="${produtos}" var="produto">
				<tr>
				 	<td><a href="${s:mvcUrl('PC#detalhe').arg(0, produto.id).build()}">${produto.titulo}</a></td>
				 	<td>${produto.descricao}</td>
				 	<td>${produto.precos }</td>
				 	<td>${produto.paginas}</td>
				</tr>
			</c:forEach>
		</table> 
	</div>
</body>
</html>