src/main/java/br/com/casadocodigo/loja/models/CarrinhoCompras.java
package br.com.casadocodigo.loja.models;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

@Component
@Scope(value=WebApplicationContext.SCOPE_SESSION)
public class CarrinhoCompras implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Map<CarrinhoItem, Integer> itens = new LinkedHashMap<>();
	
	public void add(CarrinhoItem item) {
		itens.put(item, getQuantidade(item)+1);
	}

	public int getQuantidade(CarrinhoItem item) {
		if(!itens.containsKey(item)) {
			itens.put(item, 0);
		}
		return itens.get(item);
	}
	
	public int getQuantidade(){
	    return itens.values().stream().reduce(0, (proximo, acumulador) -> (proximo + acumulador));
	}
	
	public Collection<CarrinhoItem> getItens() {
	    return itens.keySet();
	}
	
	public BigDecimal getTotal(CarrinhoItem item){
	    return item.getTotal(getQuantidade(item));
	}
	
	public BigDecimal getTotal(){
	    BigDecimal total = BigDecimal.ZERO;
	    for (CarrinhoItem item : itens.keySet()) {
	        total = total.add(getTotal(item));
	    }
	    return total;
	}

	public void remover(Integer produtoId, TipoPreco tipoPreco) {
		Produto produto = new Produto(produtoId);
		CarrinhoItem item = new CarrinhoItem(produto, tipoPreco);
		itens.remove(item);
	}
}

src/main/java/br/com/casadocodigo/loja/controllers/HomeController.java
package br.com.casadocodigo.loja.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import br.com.casadocodigo.loja.daos.ProdutoDAO;

@Controller
public class HomeController {
	
	@Autowired
	private ProdutoDAO produtoDao;
	
	@RequestMapping("/")
	@Cacheable(value="produtosHome")
    public ModelAndView index(){
		ModelAndView modelAndView = new ModelAndView("home");
		modelAndView.addObject("produtos", produtoDao.listar());
        return modelAndView;
    }
}

src/main/java/br/com/casadocodigo/loja/controllers/LoginController.java
package br.com.casadocodigo.loja.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class LoginController {
	
	@RequestMapping(value="login", method=RequestMethod.GET)
	public String loginForm(){
		return "loginForm";
	}
}

src/main/webapp/WEB-INF/views/cabecalho.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>


<header id="layout-header">
	<div class="clearfix container">
		<a href="${s:mvcUrl('HC#index').build()}" id="logo">
            <img src="https://cdn.rawgit.com/alura-cursos/spring-mvc-i-criando-aplicacoes-web-master/master/src/main/webapp/resources/imagens/cdc-logo.svg" />
        </a>
		<div id="header-content">
			<nav id="main-nav">
				<ul class="clearfix">
					<security:authorize access="isAuthenticated()">
						<li><a href="${s:mvcUrl('PC#listar').build()}" rel="nofollow">Listagem de Produtos</a></li>
					</security:authorize>
					<security:authorize access="hasRole('ROLE_ADMIN')">
    					<li><a href="${s:mvcUrl('PC#form').build()}" rel="nofollow">Cadastro de Produtos</a></li>
					</security:authorize>
					<li>
						<a href="${s:mvcUrl('CCC#itens').build()}" rel="nofollow">
							<fmt:message key="menu.carrinho">
					            <fmt:param value="${carrinhoCompras.quantidade}"/>
					        </fmt:message>
						</a>
					</li>
					<li>
						<a href="/pages/sobre-a-casa-do-codigo" rel="nofollow">
							<fmt:message key="menu.sobre"/>
						</a>
					</li>
					<li>
						<a href="/pages/perguntas-frequentes" rel="nofollow">
							<fmt:message key="menu.faq"/>
						</a>
					</li>
					<li>
					    <a href="?locale=pt" rel="nofollow">
					        <fmt:message key="menu.pt"/>
					    </a>
					</li>
					
					<li>
					    <a href="?locale=en_US" rel="nofollow">
					        <fmt:message key="menu.en"/>
					    </a>
					</li>
				</ul>
			</nav>
		</div>
    </div>
</header>
<nav class="categories-nav">
    <ul class="container">
        <li class="category">
            <a href="${s:mvcUrl('HC#index').build()}">
                <fmt:message key="navegacao.categoria.home"/>
            </a>
        </li>
        <li class="category">
            <a href="/collections/livros-de-agile">
                <fmt:message key="navegacao.categoria.agile"/>
            </a>
        </li>
        <li class="category">
            <a href="/collections/livros-de-front-end">
                <fmt:message key="navegacao.categoria.front_end"/>
            </a>
        </li>
        <li class="category">
            <a href="/collections/livros-de-games">
                <fmt:message key="navegacao.categoria.games"/>
            </a>
        </li>
        <li class="category">
            <a href="/collections/livros-de-java">
                <fmt:message key="navegacao.categoria.java"/>
            </a>
        </li>
        <li class="category">
            <a href="/collections/livros-de-mobile">
                <fmt:message key="navegacao.categoria.mobile"/>
            </a>
        </li>
        <li class="category">
            <a    href="/collections/livros-desenvolvimento-web">
                <fmt:message key="navegacao.categoria.web"/>
            </a>
        </li>
        <li class="category">
            <a href="/collections/outros">
                <fmt:message key="navegacao.categoria.outros"/>
            </a>
        </li>
    </ul>
</nav>

src/main/webapp/WEB-INF/views/erro.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %>

<tags:pageTemplate titulo="Erro Genérico">

    <section id="index-section" class="container middle">
    	<br>
        <h2>Ocorreu um erro na aplicação</h2>
    </section>
    
    <!-- 
        Mensagem: ${exception.message}
        <c:forEach items="${exception.stackTrace}" var="stk">
            ${stk}
        </c:forEach>    
    -->

</tags:pageTemplate>

src/main/webapp/WEB-INF/views/erroProdutoNaoEncontrado.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %>

<tags:pageTemplate titulo="Produto não encontrado">

    <section id="index-section" class="container middle">
    	<br>
        <h2>O produto informado não foi encontrado</h2>
    </section>

</tags:pageTemplate>

src/main/webapp/WEB-INF/views/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %>

<tags:pageTemplate titulo="Livros de Java, Android, iOS, Mobile e muito mais...">

    <section id="index-section" class="container middle">
        <h1 class="cdc-call">Últimos dias com os preços promocionais. Aproveite!</h1>
        <ul class="clearfix book-collection">
            <c:forEach items="${produtos}" var="produto">
            <li>
                <a href="${s:mvcUrl('PC#detalhe').arg(0, produto.id).build()}" class="block clearfix">
                    <h2 class="product-title">${produto.titulo}</h2>
                    <img width="143" height="202"
                        src="https://cdn.shopify.com/s/files/1/0155/7645/products/java8-featured_large.png?v=1411490181"
                        alt="Java 8 Prático" title="Java 8 Prático" />
                    <small class="buy-button">Compre</small>
                </a>
            </li>
            </c:forEach>
        </ul>

        <h2 class="cdc-call">Diferenciais da Casa do Código</h2>
        <ul id="cdc-diferenciais" class="clearfix">
            <li class="col-left">
                <h3>E-books sem DRM. Leia onde quiser</h3>
                <p>
                    <span class="sprite" id="sprite-drm"></span> 
                    Nossos e-books não possuem DRM, ou seja, você pode ler em qualquer computador, tablet e smartphone.
                </p>
            </li>
            <li class="col-right">
                <h3>Autores de renome na comunidade</h3>
                <p>
                    <span class="sprite" id="sprite-renome"></span> 
                    Autores que participam ativamente na comunidade com Open Source, listas de discussão, grupos e mais.
                </p>
            </li>
            <li class="col-left">
                <h3>Receba atualizações dos e-books</h3>
                <p>
                    <span class="sprite" id="sprite-atualizacoes"></span> 
                    Quando você    compra um e-book, automaticamente tem direito às atualizações e correções dele.
                </p>
            </li>
            <li class="col-right">
                <h3>Livros com curadoria da Caelum</h3>
                <p>
                    <span class="sprite" id="sprite-caelum"></span> 
                    Desenvolvedores    experientes que avaliam e revisam os livros constantemente.
                </p>
            </li>
        </ul>
    </section>

</tags:pageTemplate>

src/main/webapp/WEB-INF/views/loginForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Livros de Java, Android, iPhone, Ruby, PHP e muito mais - Casa do Código</title>
    <c:url value="/resources/css" var="cssPath" />
    <link rel="stylesheet" href="${cssPath}/bootstrap.min.css" />
    <link rel="stylesheet" href="${cssPath}/bootstrap-theme.min.css" />
    <style type="text/css">
        body{
            padding: 60px 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Login Casa do Código</h1>
        <form:form servletRelativeAction="/login" method="post">
            <div class="form-group">
                <label>Nome</label>
                <input type="text" name="username" class="form-control" />
            </div>
            <div class="form-group">
                <label>Senha</label>
                <input type="password" name="password" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Logar</button>
        </form:form>
    </div>
</body>
</html>